name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1️⃣ 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: 2️⃣ Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: 3️⃣ 의존성 설치
      run: npm install
    
    - name: 4️⃣ 린트 검사
      run: npm run lint
    
    - name: 5️⃣ 테스트 실행
      run: npm run test
    
    - name: 6️⃣ 빌드 테스트
      run: npm run build
    
    - name: 7️⃣ 애플리케이션 실행 테스트
      run: npm run start
