name: Hello World

# 언제 실행될지 정의
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 실행할 작업들 정의
jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: 인사말 출력
      run: |
        echo "안녕하세요! GitHub Actions 세계에 오신 것을 환영합니다!"
        echo "현재 시간: $(date)"
        echo "실행 환경: $(uname -a)"
